version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 5000
      FLASK_APP: app.py
      FLASK_ENV: development
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:ImRoot_2024@db:5432/dnd_consult
    ports:
      - "5000:5000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ImRoot_2024
      POSTGRES_DB: dnd_consult
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: